### ISSUE TITLE
USD naar EUR

### ISSUE THREAD

**Issue by JeffreyDamen** [paypronl/woocommerce-payments-plugin#45]
Hoi,

Ik ben sinds kort klant van PayPro. Er werd telefonisch aangegeven dat de Woocommerce payment gateway via PayPal USD naar EUR accepteert. De omrekening zou dan op basis van de PayPal koers gaan. Helaas krijg ik het niet voor elkaar. $10 dollar op de checkout pagina wordt €10 tijdens de PayPal betaling via PayPro. Dient hiervoor een conversie plugin gebruikt te worden?

Heb specifiek een test site met een schone WP eb Woocommerce installatie opgezet om uit te sluiten dat het aan de live website ligt.

**Comment by paypro-leon** [comment]
Wij kunnen inderdaad USD verwerken via PayPal, maar op dit moment geeft de WooCommerce plugin niet de currency mee aan onze API. We gaan dus altijd uit van EUR.

Een conversie plugin lijkt me op dit moment de makkelijkste oplossing. Je toont dan de valuta die je wilt maar settled alles in EUR. Scheelt ook conversie kosten.

PayPro zelf settled sowieso alleen in EUR.
